apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pipelines-poc
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
  stages:
    - name: pre merge
      type: jenkins
      host: https://...
      outputs: [version]
    - name: staging
      type: jenkins
      host: https://...
      outputs: [chartName]
    - name: integration
      type: spinnaker
      host: https://...
      outputs: [URL]
